### ISSUE TITLE
Bedre navn

### ISSUE THREAD

**Issue by jarib** [holderdeord/hdo-transcript-search#14]
Vi trenger et bedre navn enn «Stortingsøk». Kanskje @KJrishaug og @henrikhelmers har noen kreative ideer?

**Comment by henrikhelmers** [comment]
Det er kanskje mer i retning av "Ytringer på tinget" eller "Fra Stortingets talerstol"?

**Comment by jarib** [comment]
Mm, ja. Hadde vært kult å få inn en eller annen referanse til språk også, dette er jo på mange måter et verktøy for å visualisere språkbruk på stortinget. Og navnet på tjenesten bør kunne brukes i URLen -  xyz.holderdeord.no.

**Comment by jarib** [comment]
Litt assosiasjonslek:

ord 
tale
språk
tekst
tegn
riss
dialog
retorikk
samtale
Cicero
korpus
mening
debatt
spørsmål
verbal
tanke
argument
lingvistikk
rhetorica norvegica
lingua
sitat
diskurs
høre
lytte
snakke
prate
idé
kommunisere
møte
uttrykke

**Comment by ivarref** [comment]
Url-forslag (prefiks for holderdeord.no eller tilsvarende):

Talesøk
Talerstol
Sagtpåtinget
Tinget
Tingsøk
Talearkiv
Klartale (et slags ordspill(det motsatte av) på Tåketale)

"Talesøk" slår meg som veldig rett fram...

**Comment by ivarref** [comment]
Fullt navn kan (og bør sikkert) vera lengre og meir beskrivande enn feks
talesøk

**Comment by jarib** [comment]
En kamerat foreslår `logos.holderdeord.no`

> Logos (gresk: λόγος, av lego/legein å tale) kan bety ord, begrep, tale, forhold, resonnement, tanke, fornuft og universell verdensorden.

**Comment by jarib** [comment]
En annen ting er at vi kanskje ikke trenger samsvar mellom URL og tittel. Vi kan ha noe enkelt og lett å huske i URLen (f.eks. `tekst.holderdeord.no`), og en mer forklarende/pedagogisk tittel (f.eks. «Fra Stortingets talerstol»).

**Comment by jarib** [comment]
`korpus.holderdeord.no`

**Comment by jarib** [comment]
Forslag fra Tiina:

* Hvem sier hva
* Sagt i salen
* Taleteller
* Hvem sa hva

Noen flere URL-forslag:

* `sagt.holderdeord.no`
* `tale.holderdeord.no`
