### ISSUE TITLE
Bedre headerbilde

### ISSUE THREAD

**Issue by jarib** [holderdeord/hdo-transcript-search#15]
Vi trenger et nytt og friskt bilde synes jeg. Hjelp @henrikhelmers!

**Comment by henrikhelmers** [comment]
Siden vi først var på løven prøver jeg denne. Har også noen bilder av Stortingssalen og utsikt fra talerstolen som kanskje passer?

![header_sok](https://cloud.githubusercontent.com/assets/1570463/6203769/6be59b36-b532-11e4-9b86-e8dbfd15f408.jpg)

**Comment by henrikhelmers** [comment]
Legger også ved en høyoppløslig utgave, i tilfelle.
![love](https://cloud.githubusercontent.com/assets/1570463/6203773/9def3916-b532-11e4-9975-bd42e4c1c0af.jpg)

**Comment by jarib** [comment]
Jeg tester denne! Utsikt fra talerstolen høres forsåvidt også passende ut.
