### ISSUE TITLE
Personbilder

### ISSUE THREAD

**Issue by jarib** [holderdeord/hdo-transcript-search#28]
I liste over treff o.l. kan via HDOs API hente ut bilder på representantene. 

Vi trenger å oversette fullt navn til person-id slik den brukes på Stortinget og i vårt APIet, eventuelt legge til støtte i APIet for et oppslag basert på fullt navn.

**Comment by Andersos** [comment]
Det hadde jo vært lurt med støtte for å slå opp navn i APIet. Er det https://github.com/holderdeord/hdo-api-experiments eller https://github.com/holderdeord/hdo-site/tree/master/app/controllers/api du tenker på?

**Comment by jarib** [comment]
Siste ja!

**Comment by jarib** [comment]
Ved litt ettertanke tror jeg det er bedre om vi gjør dette oppslaget én gang som del av indekseringen, framfor hver gang vi vil rendre et bilde i tjenesten.

**Comment by jarib** [comment]
Har lagt til dette, men hot-linker til data.stortinget.no. Det har jo noen ulemper, men det gjør at vi får bilder for representanter som ikke ligger i HDOs database/API - noe som trengs for referater fra før 2009.
