### ISSUE TITLE
Bytte grafbibliotek?

### ISSUE THREAD

**Issue by jarib** [holderdeord/hdo-transcript-search#29]
C3 har noen [litt ekle problemer](https://github.com/masayuki0812/c3/issues/934) som de ikke ser ut til å addressere. Kanskje vi burde sjekke ut et annet bibliotek?

Her er noen vi kan vurdere:

* [NVD3](http://nvd3.org/)
* [Chart.js](http://www.chartjs.org/)
* [Epoch](http://fastly.github.io/epoch/)
* [Plottable](http://plottablejs.org/)

Kanskje @ivarref har noen innspill?

**Comment by ivarref** [comment]
Eg har berre erfaring med rein d3.
Utfrå websidene så synest eg nvd3 såg mest "spot on" ut for det problemet
som skal løysast.

**Comment by jarib** [comment]
Noen andre:

* [Chartist.js](http://gionkunz.github.io/chartist-js/)
* [uvCharts](http://imaginea.github.io/uvCharts/)
* [MetricsGraphics](http://metricsgraphicsjs.org/)
* [xcharts](http://tenxer.github.io/xcharts)

Chartist ser lovende ut, så tester ut den nå.

**Comment by jarib** [comment]
Jeg har nå pusha det jeg rakk med Chartist til master. Det ser fryktelig smått ut når det kombineres med Bootstrap.

![image](https://cloud.githubusercontent.com/assets/572/6263690/4e76b706-b81b-11e4-81c7-5dca65b09d65.png)

Jeg har også midlertidig fjernet muligheten for å legge til flere søkeord, det krever litt større endringer i datamodellen som sendes gjennom komponentene.

Her er det jeg har lært om å tweake Chartist-grafene:

* endre [aspectRatio-parameteret](http://gionkunz.github.io/chartist-js/getting-started.html#as-simple-as-it-can-get), f.eks. [her](https://github.com/holderdeord/hdo-transcript-search/blob/5b4984859b23e5f18f156189bc0890e002f62036/webapp/src/frontend/components/Timeline.js#L39) og [her](https://github.com/holderdeord/hdo-transcript-search/blob/5b4984859b23e5f18f156189bc0890e002f62036/webapp/src/frontend/components/TopListChart.js#L36). 
* Se hvilke options som støttes: [Bar](https://github.com/gionkunz/chartist-js/blob/6cf68d271f1e291b7a9d0fb7788c1c0464cb4d37/src/scripts/charts/bar.js#L15-82), [Line](https://github.com/gionkunz/chartist-js/blob/6cf68d271f1e291b7a9d0fb7788c1c0464cb4d37/src/scripts/charts/line.js#L17-89).
* Overstyre CSS-variabler: Chartist bruker SCSS og variabler kan overstyres [i denne fila](https://github.com/holderdeord/hdo-transcript-search/blob/5b4984859b23e5f18f156189bc0890e002f62036/webapp/src/frontend/styles/chartist.scss).

Jeg lurer også litt på om vi skal rotere de nederste grafene, gjøre de vertikale:

![image](https://cloud.githubusercontent.com/assets/572/6263716/d3f169d0-b81b-11e4-8524-dd47d5e15adc.png)

cc @henrikhelmers

**Comment by jarib** [comment]
Er ganske fornøyd med Chartist så langt. Lukker denne inntil videre.
