### ISSUE TITLE
RSS-feed / abonnement

### ISSUE THREAD

**Issue by jarib** [holderdeord/hdo-transcript-search#47]
RSS er en enkel måte for oss å tilby "abonnement" på et gitt søkeord. Men de færreste bruker det forstatt.

Kanskje finnes det en ekstern tjeneste for å lage nyhetsbrev ut av RSS-feeder. Da kunne vi sluppet den ekstra kostnaden ved å ha brukere, innlogging og lagring av søk for epost-varsling.

**Comment by Andersos** [comment]
Kanskje du tenker på noe sånt http://mailchimp.com/features/rss-to-email/ ?

**Comment by jarib** [comment]
Yes! Perfekt!

**Comment by petterreinholdtsen** [comment]
[Jari Bakken]
> RSS er en enkel måte for oss å tilby "abonnement" på et gitt
> søkeord. Men de færreste bruker det forstatt.

Jeg bruker RSS, og er veldig fornøyd med at både FiksGataMi og Alaveteli
tilbyr RSS-kilde.  Anbefaler RSS på det varmeste. :)

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by jarib** [comment]
@Andersos Eller, kanskje. 

Brukeropplevelsen hos oss bør være noe a la:

1. Gjør et søk
2. Trykk «Send meg epost ved nye innlegg»
3. Skriv inn epostadresse og lagre.

Man bør da få nye innlegg som matcher søket på epost. 

Så det kommer litt an på om:

* MailChimp har et API for å opprette RSS-to-email
* Det ikke koster all verden – og hvertfall ikke per RSS-feed, som det kan bli mange av.

Dessverre er det god forsinkelse fra noe blir sagt i salen til Stortinget tilgjengeliggjør XML-referatet, som kan legge en liten demper på denne tjenesten. Siste referat ute nå er fra 13. mai. 

@petterreinholdtsen Jepp, kommer ikke til å droppe RSS, siden det er veldig lett å implementere. Det blir et minimum.

**Comment by Andersos** [comment]
Opp til 2000 abo. eller 12 000 e-post i mnd tror jeg vi kan få gratis fra Mailchimp.
Så lenge det finnes en RSS side hos oss for søket så kan vi matche det opp mot et nyhetsbrev hos Mailchimp etter min forståelse.

**Comment by jarib** [comment]
Skal lese meg opp på det selv når jeg har overskudd :) 

Men 2000 abonnenter på ett nyhetsbrev er jo litt annerledes enn å lage 2000 nyhetsbrev med én RSS-feed hver. Mulig det blir for hackete.

Noen andre alternativer:

1. Lage en sånn RSS-til-epost-tjeneste selv. 
2. Bygge det inn i hdo-transcript-search, kanskje via å bruke [perkolering i ES](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-percolate.html).

**Comment by Andersos** [comment]
Ser for meg at det er mulig med 2000 nyhetsbrev potensielt. Slik jeg forstod det så løste vi det slik med [Hjørner](http://www.finn.no/hjorner/) at hvert Hjørne er et nyhetsbrev (rss) som sender ut til alle medlemmene. Men 2000 kan potensielt være for lite. Kjedelig å sitte på en løsning som kan koste penger. Alternativ 2 er vel omtrent slik Finn gjør lagret søk. Om man skulle gå for alternativ 1 tenker du at man løser det med en slags cron job som sjekker rssene?

**Comment by jarib** [comment]
Ja, en slags cron-jobb, men trenger et API som kan ta i mot koblingen fra epost -> feed/søkestreng og lagre den et sted. 

Kanskje en liten Node+LevelDB-tjeneste hadde gjort susen.

**Comment by jarib** [comment]
Og den må lagre når den sist sendte ut innlegg for å unngå å sende de samme flere ganger.

**Comment by jarib** [comment]
Har nå lagt til en Atom / RSS-feed: https://tale.holderdeord.no/feed?query=skatt

Den er ikke eksponert i brukergrensesnittet enda.

Flott om dere som bruker RSS aktivt kan teste det ut litt. Litt usikker på hvordan det er med referatproduksjonen nå om sommeren, det siste referatet vi har fått inn er fra 21. mai.

**Comment by petterreinholdtsen** [comment]
[Jari Bakken]
> Har nå lagt til en Atom / RSS-feed:
> https://tale.holderdeord.no/feed?query=skatt

> Den er ikke eksponert i brukergrensesnittet enda.

Hvis dere har lyst på inspirasjon, så kan dere se hvordan RSS-kilder er
lagt inn på <URL: http://www.fiksgatami.no/ > og
<URL: https://www.whatdotheyknow.com/list/successful >.

> Flott om dere som bruker RSS aktivt kan teste det ut litt. Litt
> usikker på hvordan det er med referatproduksjonen nå om sommeren, det
> siste referatet vi har fått inn er fra 21. mai.

Takk.  Jeg la noen søk inn i RSS-leseren min, så får jeg beskjed når
noen nevner noe nytt om ting jeg er interessert i. :)

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by jarib** [comment]
La det til nederst til høyre i søkeresultatet:

![image](https://cloud.githubusercontent.com/assets/572/8511615/f3bb9cde-2320-11e5-95e5-dc30708ca4c6.png)

Lukker denne og lager en egen sak for nyhetsbrev.

**Comment by jarib** [comment]
PS. Feeden gir de siste 10 innleggene som matcher søket. Antallet kan styres opp med f.eks. `?size=20`, og feeden inneholder `atom:link`-elementer for paginering. Vet ikke hvordan RSS-klienter flest forholder seg til dette.

**Comment by petterreinholdtsen** [comment]
[Jari Bakken]
> PS. Feeden gir de siste 10 innleggene som matcher søket. Antallet kan
> styres opp med f.eks. `?size=20`, og feeden inneholder
> `atom:link`-elementer for paginering. Vet ikke hvordan RSS-klienter
> flest forholder seg til dette.

Jeg bruker akregator, og den har ingen egenskaper rundt paginering.  Den
henter de som er i URL-en jeg oppgir, og arkiverer gamle som er
forsvunnet fra feeden slik at de er tilgjengelig for meg også etter at
de er fjernet fra URL-en.

Det viktigste for akregator er at ID til hver post ikke endrer seg fra
gang til gang.

-- 
Vennlig hilsen
Petter Reinholdtsen
