### ISSUE TITLE
I want transtate it to spanish

### ISSUE THREAD

**Issue by johnfelipe** [holderdeord/hdo-transcript-search#56]
Hi is possible translate it, i18n?

**Comment by jarib** [comment]
Anything is possible, but the app is not currently set up for internationalization.

It would be great if you want to take that on, but please keep me in the loop and sketch out how you would do it with a pull request that introduces internationalization into a few components. I'm unlikely to accept a patch with a lot of changes if I don't like the chosen approach.

**Comment by johnfelipe** [comment]
Its possible you set up i18n only for english and i translate it?

**Comment by jarib** [comment]
It's not a priority for me right now – sorry.

**Comment by johnfelipe** [comment]
English is not avaible?

**Comment by jarib** [comment]
That's correct.
