### ISSUE TITLE
Installing in local enviroment but next what need to do for upload my speeches

### ISSUE THREAD

**Issue by johnfelipe** [holderdeord/hdo-transcript-search#57]
http://192.168.1.64:7575/search/pct/alkohol.rus/0
show me this
![hdo](https://cloud.githubusercontent.com/assets/428820/10780971/d8e7ab92-7d10-11e5-9846-fc8990f75c00.png)

1. How upload my speeches?
2. Admin interface?
3. How change default search value?

Tnks

**Comment by jarib** [comment]
1. You need to convert them to the format I mentioned [here](https://github.com/holderdeord/hdo-transcript-search/issues/55), and index them in [elasticsearch](https://www.elastic.co/products/elasticsearch). 
2. There's no admin interface. 
3. The example searches can be changed in [examples.js](https://github.com/holderdeord/hdo-transcript-search/blob/master/webapp/config/examples.js).
