### ISSUE TITLE
Årene 2015 og 2016 vises ikke i søket

### ISSUE THREAD

**Issue by ivarref** [holderdeord/hdo-transcript-search#58]
Se f.eks. https://tale.holderdeord.no/search/pct/dagsnytt%2018/0

<img width="874" alt="screen shot 2016-01-14 at 19 33 25" src="https://cloud.githubusercontent.com/assets/74075/12333645/bfba0cf0-baf5-11e5-8bf5-07b2c2b35e04.png">

**Comment by jarib** [comment]
Vi viser med vilje ikke ufullstendige år i tidslinja. 2015 vil dukke opp så fort Stortinget publiserer et referat fra 2016 i datatjenesten.

**Comment by ivarref** [comment]
Hm. Slår meg som meget nyttig å kunne se trend for inneværende år
vs foregående.
Selv om datagrunnlaget ikke er komplett.
Og å ikke måtte vente til året er omme for å sjekke det.

For oljediagram har jeg brukt 12 month moving average en del. Det kunne
også vært et alternativ her.

**Comment by jarib** [comment]
Ser den. Vi vurderte å vise en prognose, men synes ikke det ble bra nok. 

Siden så mye av aktiviteten foregår i juni og desember (ca 47% av alle uttalte ord i 2014 kom fra disse månedene), virket det veldig misvisende å vise fram et tall overhodet i begynnelsen av året.

Vi landet på å heller holde det enkelt og ikke stille oss selv laglig til for hugg ved å ha et punkt i grafen som ville endret seg (potensielt drastisk) gjennom året.

Så får vi heller bruke anledningen til å annonsere med brask og bram at tjenesten har et nytt år med data så fort alle 2015-referatene er inne.

**Comment by ivarref** [comment]
Okay.

Eg var ikkje klar over at aktiviteten er så fokusert på to måneder. Det
endrer saken.
Kvifor er det sånn?

**Comment by jarib** [comment]
Såvidt jeg vet skyldes det at høsten går med til budsjettjobbing som så vedtas i desember, og at det oppstår en klassisk ketchupeffekt av at mange forslag utarbeides over vinteren når budsjettet er ferdig, og derfor blir behandlet i mai/juni.
